apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  
  project: default
  sources:
    # chart from helm repo
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 54.2.2
      helm:
        version: v3
        releaseName: kube-prometheus-stack
        valueFiles:
          - $values/manifests/prometheus/values.yaml
    # values from git 
    - repoURL: git@github.com:Hybeekay1/CD-with-GitOps.git
      targetRevision: HEAD
      ref: values
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true


