---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: word-press-secret
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:antonputra/lesson-158-private.git
    targetRevision: HEAD
    path: manifests/sealed-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: deployment-c
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true