apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-pass
  namespace: deployment-c
spec:
  encryptedData:
    password: AgBke++PWNgBqQlQKgiGekme9PddI/aD8/a3N/QSrNOvzcHnNz6PhPRcblmUa+kRowq8gRMlnPdjYD4cMBmeB/qMhIkIbtI3cZ6UcQ87FXIBRQE7A8RtW1B3f8GRjVLgE4O+1sR2SqvJefwtk8UW2w38CfgkdA5Kxr0ZzlxYIkmniWMcY3ykm0Z0H79kQPGNuHqJVReKrin5Gw8r0wSEb9XangnOId0VD7nTavpMlffPH/QbH2oJ/SZTl6upAgGZ+iqUyr1ihbH2ZAwphM3rIZfRyOFrk7TW6Sd7WAacCJ6DWpaoypGfgdHZs6PvjRn205+VE5mx1rceXAIfUm/Ui5qB6jsdUHnxvCKAEnJB6568powNevLv0a+wP8CKex+mObGKX2Xh28PqcRwPGXOa9jRGvXTfW9PyQvK+VwrYNxnKV0RbbIT1puGoAIz/RPfjjbIGYy4phk/XVjUvaKfgzktdrSnXmaQWtLf3H7Ax/AcoVnMK9lkP4CcHommJmz/R8CbL6yn1UuyIKWRd8X5e/VYPXZwI+jjt5nXoQaX1vsNRhxg03H2sJ6ieishJBzKrXcm6i9UrOgsrdtamsqxMs6NsQpROXuOQM+OSMi2km5YTazaCDDw4pRk54KYOxQhq7PEnAAjeZmiJOggTCOYc6cNG4bxWR6sKtBpOk5tX2mCLGA9+v5C8l0lVFj/nNwS1EO4sWWMsdNo5fdgXjA==
  template:
    metadata:
      creationTimestamp: null
      name: mysql-pass
      namespace: deployment-c
    type: Opaque

